spring:
  application:
    name: auto_web
server:
  port: 8082

# ???Selenium??
selenium:
  chrome:
    # ????
    driver-path: "C:\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe"
    # ?????????true???????false??????
    headless-mode: false
    # ?????????????true=???false=???
    close-browser-after-exec: true
  # ????????????????????
  timeout:
    seconds: 30
    wait-after-step: 500  # ????????????